services:
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/initdb:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
    env_file:
      - ./.env
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "-O", "-", "http://localhost:80/misc/ping" ]
      interval: 30s
      timeout: 10s
      start_period: 160s
      retries: 3